#!/bin/bash

GREEN=$'\033[0;32m'
YELLOW=$'\033[0;33m'
RESET=$'\033[0m'

if [ -f /etc/hostname ]; then
  hostname=$(cat /etc/hostname)
else
  hostname=$(hostname)
fi

function link() {
  # search for hostname-specific file
  if [ -f "$PWD/${hostname}.$1" ]; then
    src="$PWD/${hostname}.$1"
  else
    src="$PWD/$1"
  fi
  dir="$2"
  dest="$2/$3"

  msg_linked="${GREEN}Linked $src to $dest${RESET}"
  msg_exists="${YELLOW}File $dest already exists, skipping${RESET}"

  mkdir -p "$dir"
  if [ -L "$dest" ]; then
    if [ "$(readlink "$dest")" == "$src" ]; then
      # It's already a correct symlink
      echo "$msg_linked"
    elif [ ! -e "$(readlink "$dest")" ]; then
      # It's a dangling symlink
      rm "$dest"
      ln -s "$src" "$dest"
      echo "$msg_linked"
    else
      # It's a symlink but points to the another place
      echo "$msg_exists"
    fi
  elif [ -e "$dest" ]; then
    if [ -d "$src" ] && [ -d "$dest" ]; then
      # Existing directory: skip and warn
      echo "$msg_exists"
    elif [ -f "$src" ] && [ -f "$dest" ] && cmp -s "$src" "$dest"; then
      # Files are identical; replace with symlink
      rm "$dest"
      ln -s "$src" "$dest"
      echo "$msg_linked"
    else
      # Destination exists and differs; skip
      echo "$msg_exists"
    fi
  else
    # It doesn't exist; create the symlink
    ln -s "$src" "$dest"
    echo "$msg_linked"
  fi
}

link "init.vim"       "$HOME/.config/nvim"      "init.vim"
link "zshrc"          "$HOME"                   ".zshrc"
link "profile"        "$HOME"                   ".profile"
link "Xresources"     "$HOME"                   ".Xresources"
link "gitconfig"      "$HOME"                   ".gitconfig"
link "xprofile"       "$HOME"                   ".xprofile"
link "i3.conf"        "$HOME/.config/i3"        "config"
link "i3status.conf"  "$HOME/.config/i3status"  "config"
link "latexmkrc"      "$HOME/.config/latexmk"   "latexmkrc"
link "alacritty.toml" "$HOME/.config/alacritty" "alacritty.toml"
link "kime-icons/kime-hangul-black.png" "$HOME/.local/share/icons/hicolor/16x16/apps" "kime-hangul-black.png"
link "kime-icons/kime-hangul-white.png" "$HOME/.local/share/icons/hicolor/16x16/apps" "kime-hangul-white.png"
link "kime-icons/kime-latin-black.png"  "$HOME/.local/share/icons/hicolor/16x16/apps" "kime-latin-black.png"
link "kime-icons/kime-latin-white.png"  "$HOME/.local/share/icons/hicolor/16x16/apps" "kime-latin-white.png"
link "kime.yaml"      "$HOME/.config/kime"      "config.yaml"
link "hyprland.conf"  "$HOME/.config/hypr"      "hyprland.conf"
link "ironbar.toml"   "$HOME/.config/ironbar"   "config.toml"
link "ironbar.css"    "$HOME/.config/ironbar"   "style.css"
link "tmux.conf"      "$HOME/.config/tmux"      "tmux.conf"
link "here"           "$HOME/.local/bin"        "here"
link "vim"    	      "$HOME"                   ".vim"
link "kitty.conf"     "$HOME/.config/kitty"     "kitty.conf"
