[arch]
packages = [
  "7zip",
  "alacritty",
  "arandr",
  "awww",
  "base",
  "base-devel",
  "basedpyright-bin",
  "bat",
  "bdf-unifont",
  "chromium",
  "claude-code",
  "direnv",
  "dmenu",
  "dmidecode",
  "edk2-shell",
  "efivar",
  "elan-lean",
  "fcitx5",
  "fcitx5-configtool",
  "fcitx5-hangul",
  "fd",
  "feh",
  "firefox",
  "flameshot",
  "foot",
  "fuse2",
  "fzf",
  "ghostty",
  "gimp",
  "git",
  "gnome-keyring",
  "grim",
  "gvim",
  "hyprland",
  "hyprlock",
  "hyprpaper",
  "hyprshutdown",
  "imagemagick",
  "imv",
  "ironbar",
  "jq",
  "kitty",
  "libayatana-appindicator",
  "libreoffice-fresh",
  "libva-utils",
  "libxcrypt-compat",
  "linux",
  "lua-language-server",
  "man-db",
  "man-pages",
  "metapac",
  "mpv",
  "mysql-workbench",
  "neovim",
  "network-manager-applet",
  "networkmanager",
  "nix",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "nvidia-open",
  "nvidia-settings",
  "nvidia-utils",
  "opam",
  "openai-codex",
  "otf-stix",
  "pacman-contrib",
  "pavucontrol",
  "podman",
  "podman-compose",
  "postgresql",
  "pulseaudio",
  "python-cairo",
  "python-gobject",
  "python-pip",
  "python-pipx",
  "python-tqdm",
  "qt6-svg",
  "reflector",
  "ripgrep",
  "rofi",
  "ruff",
  "rust",
  "sddm",
  "slurp",
  "stow",
  "stylua",
  "sudo",
  "swaks",
  "tesseract",
  "tesseract-data-kor",
  "thunderbird",
  "tk",
  "tmux",
  "transmission-cli",
  "tree",
  "tree-sitter-cli",
  "ttf-d2coding",
  "ttf-firacode-nerd",
  "ttf-inconsolata",
  "ttf-jetbrains-mono",
  "ttf-juliamono",
  "ttf-kopub",
  "ttf-kopubworld",
  "uwsm",
  "vulkan-nouveau",
  "wakeup-triggers",
  "waybar",
  "webcord-bin",
  "wev",
  "wl-clipboard",
  "xcompmgr",
  "xorg-mkfontscale",
  "xorg-xdpyinfo",
  "xorg-xev",
  "xorg-xfontsel",
  "xorg-xlsfonts",
  "xorg-xrandr",
  "xorg-xrdb",
  "xsel",
  "yay",
  "yazi",
  "zathura",
  "zathura-pdf-mupdf",
  "zip",
  "zotero-bin",
  "zsh",
]

[pnpm]
packages = [
  "@fsouza/prettierd",
  "prettier",
  "typescript",
  "typescript-language-server",
]
